config/routes.rb
Photograph::Application.routes.draw do
  resources :comment_walls
  
  resources :followers
  
  resources :user_profiles do
    member do
      get "uploaded"
      get "wall"
    end
  end

  resources :photos do
    collection do
      get "search"
      get "all"
      get "my_favorites"
      get "my_photos"
    end

    member do
      get "all_photos/detail"
    end
  end

  devise_for :users

  resources :categories

  root :to => 'photos#index'

end

app/models/user_profile.rb
class UserProfile < ActiveRecord::Base
  belongs_to :user
  attr_accessible :avatar, :birthday, :description, :firstname, :gender, :job, :lastname, :user_id
  mount_uploader :avatar, AvatarUploader
  has_many :comment_walls
  # has_many :user_comment_walls, through: :comment_walls, source: :user
end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
  # GET /user_profiles
  # GET /user_profiles.json
  def index
    @user_profiles = UserProfile.all
    if user_signed_in?
      @user_profile = UserProfile.where(['user_id = ?', current_user.id])
    end

    # respond_to do |format|
    #   format.html # index.html.erb
    #   format.json { render json: @user_profiles }
    # end
  end

  # GET /user_profiles/1
  # GET /user_profiles/1.json
  def show
    @user_profile = UserProfile.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user_profile }
    end
  end

  # GET /user_profiles/new
  # GET /user_profiles/new.json
  def new
    @user_profile = UserProfile.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user_profile }
    end
  end

  # GET /user_profiles/1/edit
  def edit
    @user_profile = UserProfile.find(params[:id])
  end

  # POST /user_profiles
  # POST /user_profiles.json
  def create
    params[:user_profile][:user_id] = current_user.id
    @user_profile = UserProfile.new(params[:user_profile])

    respond_to do |format|
      if @user_profile.save
        format.html { redirect_to @user_profile, notice: 'User profile was successfully created.' }
        format.json { render json: @user_profile, status: :created, location: @user_profile }
      else
        format.html { render action: "new" }
        format.json { render json: @user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /user_profiles/1
  # PUT /user_profiles/1.json
  def update
    @user_profile = UserProfile.find(params[:id])
    if @user_profile.update_attributes(params[:user_profile])
      redirect_to @user_profile
    else
      render action: "edit"
    end

    # respond_to do |format|
    #   if @user_profile.update_attributes(params[:user_profile])
    #     format.html { redirect_to @user_profile, notice: 'User profile was successfully updated.' }
    #     format.json { head :no_content }
    #   else
    #     format.html { render action: "edit" }
    #     format.json { render json: @user_profile.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /user_profiles/1
  # DELETE /user_profiles/1.json
  def destroy
    @user_profile = UserProfile.find(params[:id])
    @user_profile.destroy

    respond_to do |format|
      format.html { redirect_to user_profiles_url }
      format.json { head :no_content }
    end
  end

  def uploaded
    @user_profile = UserProfile.find(params[:id])

    if user_signed_in?
      @is_followed_by_current_user = Follower.is_followed_by_current_user(current_user.id, @user_profile.user_id)
      @follower = Follower.new
    end

    @photos = @user_profile.user.photos
    if @photos.class == Array
      @photos = Kaminari.paginate_array(@photos).page(params[:page]).per(18)
    else
      @photos = @photos.page(params[:page]).per(18)
    end
  end

  def wall
    @user_profile = UserProfile.find(params[:id])

    if user_signed_in?
      @is_followed_by_current_user = Follower.is_followed_by_current_user(current_user.id, @user_profile.user_id)
      @follower = Follower.new
    end
    @comment_wall = CommentWall.new
    # @comment_walls = CommentWall.list_comment_walls_by_user_profile(@user_profile.user_id)
    @comments = @user_profile.comment_walls
    if @comments.class == Array
      @comments = Kaminari.paginate_array(@comments).page(params[:page]).per(4)
    else
      @comments = @photos.page(params[:page]).per(4)
    end
  end
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/views/user_profiles/_form.html.haml
= simple_form_for(@user_profile, html: {:multipart => true, :class => 'form-horizontal'}) do |f|
  = f.error_notification

  .form-inputs
    = f.input :firstname
    = f.input :lastname
    = f.input :description, input_html: {:size => "50x6"}
    = f.input :job, collection: ["IT", "Teacher", "Artist", "Doctor", "Worker"], include_blank: false
    = f.input :gender, as: :select, collection: [[true, 'Male'], [false, 'Female']], value_method: :first, label_method: :last, include_blank: false
    = f.input :birthday
    = f.input :avatar, as: :file

  .form-actions
    = f.button :submit

app/views/user_profiles/_profile.html.haml
= image_tag(@user_profile.avatar_url.to_s, alt: "user avatar", class: "avatar-display")

.user_profile-info
  %p
    %b Firstname:
    = @user_profile.firstname
  %p
    %b Lastname:
    = @user_profile.lastname
  %p
    %b Description:
    = @user_profile.description
  %p
    %b Job:
    = @user_profile.job
  %p
    %b Gender:
    = @user_profile.gender
  %p
    %b Birthday:
    = @user_profile.birthday
  - if user_signed_in?
    - if current_user.id == @user_profile.user_id
      %p= link_to "edit", edit_user_profile_path(@user_profile), class: "btn btn-default btn-xs"
    - else
      - if @is_followed_by_current_user == nil
        %p
          = simple_form_for @follower do |f|
            = f.hidden_field :followee_id, :value => @user_profile.user_id
            = f.submit "follow", :id => "Follow"
      - else
        %p= link_to "unfollow", follower_path(@is_followed_by_current_user), class: "btn btn-default btn-xs",
              method: :delete,
              data: { confirm: 'Are you sure?' }, :authenticity_token => form_authenticity_token
.user-nav
  %ul
    %li= link_to "Uploaded", uploaded_user_profile_path(@user_profile)
    %li= link_to "Followees", uploaded_user_profile_path(@user_profile)
    %li= link_to "Following", uploaded_user_profile_path(@user_profile)
    %li= link_to "Wall", wall_user_profile_path(@user_profile)

app/views/user_profiles/edit.html.haml
%h1.form-title Editing user_profile

= render 'form'

= link_to 'Show', uploaded_user_profile_path(@user_profile)
\|
= link_to 'Back', user_profiles_path

app/views/user_profiles/index.html.haml
%h1.form-title Listing user_profiles

%table.table
  %tr
    %th Firstname
    %th Lastname
    %th Description
    %th Job
    %th Gender
    %th Birthday
    %th Avatar
    %th User
    %th
    %th
    %th

  - @user_profiles.each do |user_profile|
    %tr
      %td= user_profile.firstname
      %td= user_profile.lastname
      %td= user_profile.description
      %td= user_profile.job
      %td
        - if user_profile.gender == true
          male
        - else
          female
      %td= user_profile.birthday
      %td= image_tag(user_profile.avatar_url(:thumb).to_s, alt: "user avatar")
      %td= user_profile.user.username
      %td= link_to 'Show', uploaded_user_profile_path(user_profile)
      %td= link_to 'Edit', edit_user_profile_path(user_profile)
      %td= link_to 'Destroy', user_profile, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'Create your profile', new_user_profile_path

app/views/user_profiles/new.html.haml
%h1.form-title New user_profile

= render 'form'

= link_to 'Back', user_profiles_path

app/views/user_profiles/show.html.haml
%p#notice= notice

%p
  %b Firstname:
  = @user_profile.firstname
%p
  %b Lastname:
  = @user_profile.lastname
%p
  %b Description:
  = @user_profile.description
%p
  %b Job:
  = @user_profile.job
%p
  %b Gender:
  = @user_profile.gender
%p
  %b Birthday:
  = @user_profile.birthday
%p
  %b Avatar:
  = image_tag(@user_profile.avatar_url.to_s, alt: "user avatar")
%p
  %b User:
  = @user_profile.user.username

= link_to 'Edit', edit_user_profile_path(@user_profile)
\|
= link_to 'Back', user_profiles_path

app/views/user_profiles/uploaded.html.haml
= render "/user_profiles/profile"

.display-grid-photos
  - @photos.each do |photo|
    %p.grid-photos
      = link_to image_tag(photo.image_url(:thumb).to_s, :alt => photo.name), photo
      - if user_signed_in? && current_user.id == photo.user.id
        = link_to 'Edit', edit_photo_path(photo)
        \|
        = link_to 'Destroy', photo, :method => :delete, :data => { :confirm => 'Are you sure?' }

= paginate @photos, :theme => 'twitter-bootstrap'

app/views/user_profiles/wall.html.haml
= render "/user_profiles/profile"

.comment-post
  = render "/comment_walls/form", :user_profile_id => @user_profile.id

/ = render @user_profile.comment_walls
.comment-posted
  - i = 1
  - @comments.each do |comment_wall|
    - if i%2 == 0
      %p.comment-posted-even.clearfix
        = image_tag(comment_wall.user.user_profile.avatar_url(:thumb).to_s, alt: "user avatar")
        %textarea= comment_wall.body

    - else
      %p.clearfix
        = image_tag(comment_wall.user.user_profile.avatar_url(:thumb).to_s, alt: "user avatar")
        %textarea= comment_wall.body
    - i = i + 1

= paginate @comments, :theme => 'twitter-bootstrap'