config/routes.rb
Photograph::Application.routes.draw do
  resources :comment_walls
  
  resources :followers
  
  resources :user_profiles do
    member do
      get "uploaded"
      get "wall"
    end
  end

  resources :photos do
    collection do
      get "search"
      get "all"
      get "my_favorites"
      get "my_photos"
    end

    member do
      get "all_photos/detail"
    end
  end

  devise_for :users

  resources :categories

  root :to => 'photos#index'

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  attr_accessible :info, :name, :category_id, :user_id, :image
  mount_uploader :image, ImageUploader
  validates :name, presence: true
  validates :category_id, presence: true
  validates :image, presence: true

  def self.search_by_name(search)
  	if search
      # sql = "select * from photos where name like '%" + search + "%'"
  		sql = "select * from photos where name like '%#{search}%'"
      # sql = "select * 
      #       from (
      #         select p.*, count(l.id) as total_likes, dense_rank() over (order by count(l.id) desc) as rank
      #         from photos as p left join like_dislikes as l on p.id = l.photo_id
      #         group by p.id
      #         order by p.id) as T
      #       where T.name like '%#{search}%'"

  		Photo.find_by_sql(sql)
  	else
      Photo.all
  		# sql = "select p.*, count(l.id) as total_likes, dense_rank() over (order by count(l.id) desc) as rank
    #       from photos as p left join like_dislikes as l on p.id = l.photo_id
    #       group by p.id
    #       order by p.id"
    #   Photo.find_by_sql(sql)
  	end

  	# if search
	  #   where 'name LIKE ?', "%#{search}%"
	  # else
	  #   scoped
	  # end
  end

  def self.related_photo(category_id, current_photo_id)
    Photo.where(['category_id = ? and id != ?', category_id, current_photo_id])
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show, :all]
  # GET /photos
  # GET /photos.json
  def index
    # @photos = Photo.all
    # @photos = Photo.search_by_name(params[:photo_name]).paginate(:page => params[:page])
    # @photos = Photo.search_by_name(params[:search]).page(params[:page])
    @photos = Photo.search_by_name(params[:search])
    if @photos.class == Array
      @photos = Kaminari.paginate_array(@photos).page(params[:page]).per(20)
    else
      @photos = @photos.page(params[:page]).per(20)
    end

    # respond_to do |format|
    #   format.html # index.html.erb
    #   format.json { render json: @photos }
    # end
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    @photo = Photo.find(params[:id])
    @category = Category.find(@photo.category_id)
    @photos = Photo.related_photo(@category.id, @photo.id)
    # respond_to do |format|
    #   format.html # show.html.erb
    #   format.json { render json: @photo }
    # end
  end

  # GET /photos/new
  # GET /photos/new.json
  def new
    @photo = Photo.new

    # respond_to do |format|
    #   format.html # new.html.erb
    #   format.json { render json: @photo }
    # end
  end

  # GET /photos/1/edit
  def edit
    @photo = Photo.find(params[:id])
  end

  # POST /photos
  # POST /photos.json
  def create
    params[:photo][:user_id] = current_user.id
    @photo = Photo.new(params[:photo])

    if @photo.save
        redirect_to photos_path, notice: 'Photo was successfully created.'
    else
      render "new"
    end

    # respond_to do |format|
    #   if @photo.save
    #     format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
    #     format.json { render json: @photo, status: :created, location: @photo }
    #   else
    #     format.html { render action: "new" }
    #     format.json { render json: @photo.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PUT /photos/1
  # PUT /photos/1.json
  def update
    @photo = Photo.find(params[:id])

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to photos_url }
      format.json { head :no_content }
    end
  end

  def all
    @photo = Photo.first
    @category = Category.find(@photo.category_id)
    @photos = Photo.all
    if @photos.class == Array
      @photos = Kaminari.paginate_array(@photos).page(params[:page]).per(20)
    else
      @photos = @photos.page(params[:page]).per(20)
    end
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.haml
= simple_form_for(@photo, :html => {:multipart => true, :class => 'form-horizontal'}) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name, :required => true, input_html: {id: "photo-name"}
    = f.input :info, input_html: {:size => "50x6"}
    = f.association :category, prompt: "Choose category", :required => true, input_html: {id: "category-id"}
    = f.input :image, as: :file, :required => true, input_html: {id: "image-path"}
    / = f.association :user
    / f.association :roles,   as: :check_boxes
    / f.association :company, label_method: :company_name, value_method: :id, include_blank: false
    / f.association :company, collection: Company.active.all(order: 'name'), prompt: "Choose a Company"
    / f.association :company, as: :radio_buttons

  .form-actions
    = f.button :submit, id: "submit-photo"

app/views/photos/all.html.haml
%p#notice= notice

= image_tag(@photo.image_url.to_s, :alt => @photo.name, :class => "photo-display")

.photo-info
  %p
    %b Name:
    = @photo.name
  %p
    %b Info:
    = @photo.info
  %p
    %b Category:
    = @photo.category.name
  %p
    %b User:
    = @photo.user.username
  - if user_signed_in? && current_user.id == @photo.user.id
    = link_to 'Edit', edit_photo_path(@photo)
    \|
  = link_to 'Back', photos_path

.photo-nav
  %ul
    %li= link_to "My Favorites", all_photos_path
    %li= link_to "My Photos", all_photos_path
    %li= link_to "All Photos", all_photos_path

app/views/photos/edit.html.haml
%h1.form-title Editing photo

= render 'form'

= link_to 'Show', @photo
\|
= link_to 'Back', photos_path

app/views/photos/index.html.haml
/ %h1.form-title Listing photos
/ / = paginate @photos
/ / = paginate @photos, window: 2
/ / = paginate @photos, outer_window: 1
/ / = paginate @photos, :left => 1, :right => 3
/ = paginate @photos, :theme => 'twitter-bootstrap'
/ / = paginate @photos, :theme => 'twitter-bootstrap-3'
/ / = paginate @photos, :theme => 'twitter-bootstrap-3', :pagination_class => "pagination-sm"
/ / = paginate @photos, :theme => 'twitter-bootstrap', :pagination_class => "pagination-small pagination-centered"
/ %p= page_entries_info @photos

/ .display-grid-photos
/   - @photos.each do |photo|
/     %p.grid-photos
/       = link_to image_tag(photo.image_url(:thumb).to_s, :alt => photo.name), photo
/       - if user_signed_in? && current_user.id == photo.user.id
/         = link_to 'Edit', edit_photo_path(photo)
/         \|
/         = link_to 'Destroy', photo, :method => :delete, :data => { :confirm => 'Are you sure?' }
/ = link_to 'New Photo', new_photo_path

/ %ul.bxslider
#banner-slide
  %ul.bjqs
    - @photos.each do |photo|
      %li= image_tag(photo.image_url.to_s, :alt => photo.name)

/ - i = 0
/ #bx-pager
/   - @photos.each do |photo|
/     %a{"data-slide-index" => "0", href: ""}
/       %img{src: photo.image_url(:thumb).to_s}
/     - i = i + 1

app/views/photos/new.html.haml
%h1.form-title New photo

= render 'form'

= link_to 'Back', photos_path

app/views/photos/show.html.haml
%p#notice= notice

= image_tag(@photo.image_url.to_s, :alt => @photo.name, :class => "photo-display")

.photo-info
  %p
    %b Name:
    = @photo.name
  %p
    %b Info:
    = @photo.info
  %p
    %b Category:
    = @photo.category.name
  %p
    %b User:
    = @photo.user.username
  - if user_signed_in? && current_user.id == @photo.user.id
    = link_to 'Edit', edit_photo_path(@photo)
    \|
  = link_to 'Back', photos_path

#related-photos
  %h3 Related Photos:
  - @photos.each do |photo|
    %p.grid-photos
      = link_to image_tag(photo.image_url(:thumb).to_s, :alt => photo.name), photo